# -*- coding: utf-8 -*-
"""ML HW 5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14aRQS_Cq_BOUXb2CXsLEOHPt8nnPJCY-
"""

import numpy as np

def scaled_dot_product_attention(Q, K, V):
    scores = Q @ K.T
    d_k = K.shape[1]
    scores = scores / np.sqrt(d_k)

    # softmax
    exp_scores = np.exp(scores - np.max(scores, axis=1, keepdims=True))
    attention_weights = exp_scores / np.sum(exp_scores, axis=1, keepdims=True)

    context = attention_weights @ V
    return attention_weights, context

# Example small matrices
Q = np.array([[1, 0, 1]])     # shape (1, 3)
K = np.array([[1, 0, 1],
              [0, 1, 0],
              [1, 1, 0]])     # shape (3, 3)

V = np.array([[1, 2],
              [3, 4],
              [5, 6]])        # shape (3, 2)

# Run attention
att_weights, ctx = scaled_dot_product_attention(Q, K, V)

print("Attention Weights:\n", att_weights)
print("\nContext Vector:\n", ctx)

import torch
import torch.nn as nn

# -----------------------------
# Simple Transformer Encoder Block
# -----------------------------
class SimpleTransformerEncoderBlock(nn.Module):
    def __init__(self, d_model=128, num_heads=8, dim_ff=512, dropout=0.1):
        super().__init__()

        # Multi-head self-attention
        self.self_attn = nn.MultiheadAttention(
            embed_dim=d_model,
            num_heads=num_heads,
            batch_first=True
        )

        # Feed-forward network
        self.ffn = nn.Sequential(
            nn.Linear(d_model, dim_ff),
            nn.ReLU(),
            nn.Linear(dim_ff, d_model)
        )

        # Add & Norm layers
        self.norm1 = nn.LayerNorm(d_model)
        self.norm2 = nn.LayerNorm(d_model)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        # ---- Self-attention ----
        attn_out, _ = self.self_attn(x, x, x)
        x = self.norm1(x + self.dropout(attn_out))  # Add & Norm

        # ---- Feed-forward ----
        ffn_out = self.ffn(x)
        x = self.norm2(x + self.dropout(ffn_out))    # Add & Norm

        return x

# -----------------------------
# Test the encoder block
# -----------------------------

# Initialize encoder
encoder = SimpleTransformerEncoderBlock(d_model=128, num_heads=8)

# Input: batch of 32 sentences, each 10 tokens, each token embedding dim = 128
x = torch.randn(32, 10, 128)

# Forward pass
output = encoder(x)

# Print results
print("OUTPUT TENSOR:\n", output)
print("\nOUTPUT SHAPE:", output.shape)